# Generated by Django 5.0.6 on 2024-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadaar_number', models.BigIntegerField()),
                ('pan_number', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
    ]
